### ISSUE TITLE
tokenizer does not have a padding token

### ISSUE THREAD

**Issue by razikov** [ai-forever/MERA#9]
Модели (вся серия мистралей и их производные) у которых не определён pad токен падают на бенчмарках: `rudetox, use, rumodar, multiq, rumultiar, simplear, chegeka` с ошибкой:

> ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`.

Запускал так:
```
CUDA_VISIBLE_DEVICES=1 python main.py --model hf-causal-experimental --model_args pretrained=mistralai/Mistral-7B-v0.1,dtype=auto,max_length=11500 \
--device cuda --output_base_path="$PWD/mera_results/Mistral-7B-v0.1_defaults" --batch_size=1 \
--inference --write_out --no_cache --tasks rudetox \
--output_path="$PWD/mera_results/Mistral-7B-v0.1_defaults/rudetox_result.json"
```

Trace
```
Traceback (most recent call last):
  File ".../MERA/lm-evaluation-harness/main.py", line 141, in <module>
    main()
  File ".../MERA/lm-evaluation-harness/main.py", line 98, in main
    results = evaluator.simple_evaluate(
  File ".../MERA/lm-evaluation-harness/lm_eval/utils.py", line 238, in _wrapper
    return fn(*args, **kwargs)
  File ".../MERA/lm-evaluation-harness/lm_eval/evaluator.py", line 145, in simple_evaluate
    rudetox_results = evaluate(
  File ".../MERA/lm-evaluation-harness/lm_eval/utils.py", line 238, in _wrapper
    return fn(*args, **kwargs)
  File ".../MERA/lm-evaluation-harness/lm_eval/evaluator.py", line 1033, in evaluate
    resps = getattr(lm, reqtype)([req.args for req in reqs])
  File ".../MERA/lm-evaluation-harness/lm_eval/models/huggingface.py", line 504, in greedy_until
    token_context = self.tok_encode_batch(context)
  File ".../MERA/lm-evaluation-harness/lm_eval/models/huggingface.py", line 431, in tok_encode_batch
    return self.tokenizer(
  File ".../MERA/lm-evaluation-harness/venv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2803, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File ".../MERA/lm-evaluation-harness/venv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2889, in _call_one
    return self.batch_encode_plus(
  File ".../MERA/lm-evaluation-harness/venv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 3071, in batch_encode_plus
    padding_strategy, truncation_strategy, max_length, kwargs = self._get_padding_truncation_strategies(
  File ".../MERA/lm-evaluation-harness/venv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2708, in _get_padding_truncation_strategies
    raise ValueError(
ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`.
```

Раз бенчмарк добавлен в лидерборду, значит как-то уже исправляли?

**Comment by artemorloff** [comment]
Здравствуйте, @razikov 
действительно, модели семейства мистраль не могут не запускаться в следствие отсутствия у них pad_token. Для корректного запуска мы локально в tokenizer_config.json мистрали прописывали:
`"pad_token": "</s>",`
С данной правкой pad_token заменяется на eos_token и модель корректно скорится на МЕРЕ!
